### ISSUE TITLE
is this coming soon

### ISSUE THREAD

**Issue by Lartu** [mfachal/sanguche#1]
hi thewe the weadme says dis is coming soon is it coming soon i want to know since dis has been created two years ago k thx bye (´・(oo)・｀)

xoxoxo u////u

**Comment by Lartu** [comment]
bug pls fix it doesn't compile help me

**Comment by Lartu** [comment]
heres an answer to something https://stackoverflow.com/questions/621987… hope it helps emu

**Comment by Lartu** [comment]
<img src="https://media1.tenor.com/images/e9c18f8cb8b86ed79bbbdebfe65d2583/tenor.gif?itemid=7483300">

**Comment by mfachal** [comment]
soon (tm)

**Comment by Lartu** [comment]
is dis soon yet (＞﹏＜)

uwu sowwy
